# Generated by Django 6.1 on 2026-08-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries (Ration / Household)'), ('Utilities', 'Utilities (Bills: Electricity, Gas, Water, Net)'), ('Rent', 'Rent (Ghar / Dukaan ka Kiraya)'), ('Transport', 'Transport / Petrol / Fuel'), ('Food', 'Food & Dining Out'), ('Health', 'Health & Medical'), ('Education', 'Education / School / College Fees'), ('Shopping', 'Shopping & Clothes'), ('Entertainment', 'Entertainment & Outing'), ('Savings', 'Savings & Investment'), ('Other', 'Other / Miscellaneous')], default='Other', max_length=50),
        ),
    ]
