# Generated by Django 6.1 on 2026-08-29 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_user_income_user_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries / Ration'), ('Utilities', 'Utilities / Bills'), ('Rent', 'Rent / Kiraya'), ('Transport', 'Transport / Petrol'), ('Food', 'Food & Dining Out'), ('Health', 'Health & Medical'), ('Education', 'Education / Fees'), ('Shopping', 'Shopping & Clothes'), ('Entertainment', 'Entertainment'), ('Savings', 'Savings'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Groceries', 'Groceries / Ration'), ('Utilities', 'Utilities / Bills'), ('Rent', 'Rent / Kiraya'), ('Transport', 'Transport / Petrol'), ('Food', 'Food & Dining Out'), ('Health', 'Health & Medical'), ('Education', 'Education / Fees'), ('Shopping', 'Shopping & Clothes'), ('Entertainment', 'Entertainment'), ('Savings', 'Savings'), ('Other', 'Other')], max_length=50)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('PKR', 'Rs. (PKR)'), ('USD', '$ (USD)'), ('AED', 'AED (Dirham)'), ('SAR', 'SAR (Riyal)'), ('EUR', '€ (Euro)')], default='PKR', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
