# Generated by Django 6.1 on 2026-08-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_recurringbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringbill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CategoryBudget',
        ),
        migrations.DeleteModel(
            name='RecurringBill',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
